export enum WeatherType {
  TEMP = "temperature",
  TEMP_APPARENT = "temperatureApparent",
  DEW_POINT = "dewPoint",
  HUMIDITY = "humidity",
  WIND_SPEED = "windSpeed",
  WIND_DIRECTION = "windDirection",
  WIND_GUST = "windGust",
  PRESSURE_SURFACE = "pressureSurfaceLevel",
  PRESSURE_SEA = "pressureSeaLevel",
  PRECIPITATION_INTENSITY = "precipitationIntensity",
  RAIN_INTENSITY = "rainIntensity",
  FREEZING_RAIN_INTENSITY = "freezingRainIntensity",
  SNOW_INTENSITY = "snowIntensity",
  SLEET_INTENSITY = "sleetIntensity",
  PRECIPITATION_PROBABILITY = "precipitationProbability",
  PRECIPITATION_TYPE = "precipitationType",
  RAIN_ACCUMULATION = "rainAccumulation",
  SNOW_ACCUMULATION = "snowAccumulation",
  SNOW_ACCUMULATION_LWE = "snowAccumulationLwe",
  SNOW_DEPTH = "snowDepth",
  SLEET_ACCUMULATION = "sleetAccumulation",
  SLEET_ACCUMULATION_LWE = "sleetAccumulationLwe",
  ICE_ACCUMULATION = "iceAccumulation",
  ICE_ACCUMULATION_LWE = "iceAccumulationLwe",
  SUNRISE_TIME = "sunriseTime",
  SUNSET_TIME = "sunsetTime",
  VISIBILITY = "visibility",
  CLOUD_COVER = "cloudCover",
  CLOUD_BASE = "cloudBase",
  CLOUD_CEILING = "cloudCeiling",
  MOON_PHASE = "moonPhase",
  UV_INDEX = "uvIndex",
  UV_HEALTH_CONCERNS = "uvHealthConcern",
  THUNDERSTORM_PROBABILITY = "thunderstormProbability",
  EZ_HEAT_STRESS_INDEX = "ezHeatStressIndex",
  // Weather codes
  WEATHER_CODE = "weatherCode",
  WEATHER_CODE_DAY = "weatherCodeDay",
  WEATHER_CODE_NIGHT = "weatherCodeNight",
  WEATHER_CODE_FULL_DAY = "weatherCodeFullDay",
}
export type WeatherLayer = {
  id: WeatherType;
  name?: string;
};
